### ISSUE TITLE
Conflict with jest and react-use-scrollspy

### ISSUE THREAD

**Issue by karzQ** [dxc-technology/halstack-react#169] opened 2021-02-17 09:37 UTC
Hello everyone, my issue is simple :

**Describe the bug**
When I try to start my Unit Tests, it'll be in error when it pass on the component which contains DXC components.

**To Reproduce**
1. Create a component with some ```DXC Halstack-react components```.
2. Create a ```component.specs.js``` file and add some unit tests.
3. Start the tests with ```npm run``` test or **yarn test**

**Expected behavior**
When the component will be tested you'll get an error related to EcmaScript Modules, from ```TabsForSections```.

**Screenshots**
![image](https://user-images.githubusercontent.com/32488393/108184078-15d82d80-710b-11eb-8feb-8f5e6566bf33.png)

Let me know if you need more informations.

EDIT: A ```component.test.js``` not ```specs```.

**Comment by jsardid** [comment] 2021-04-07 18:55
Hi @karzQ,

We haven't been able to reproduce this issue. Can you confirm if this is still happening for you?

**Comment by jsardid** [comment] 2021-04-13 09:54
I'm closing this one.
Please reopen it if it keeps happening.

**Comment by jsardid** [comment] 2021-05-18 08:01
Reopening since I've been able to reproduce this.
Steps:
1) npx create-react-app my-app
2) cd my-app/
3) npm install @dxc-technology/halstack-react styled-components
4) use any Halstack component in App.js
5) npm run test src/App.test.js

Adding this to the package.json fixes it, but this shouldn't be required in the first place:
```json
"jest": {
    "transformIgnorePatterns": [
      "/node_modules/(?!react-use-scrollspy).+\\.js$"
    ]
}
```

**Comment by jsardid** [comment] 2021-12-29 11:13
Removed the dependency with react-scroll-spy. The temporary solution described on my previous comment is no longer needed.

**Closed by jsardid** 2021-12-29 11:13 UTC
Labels: enhancement, up-for-grabs
