### ISSUE TITLE
Autosuggest - Bug!

### ISSUE THREAD

**Issue by HanojHanu** [dxc-technology/halstack-react#1414] opened 2022-12-07 17:01 UTC
**Describe the bug**

**To Reproduce**
Include steps to reproduce the behaviour.
``` js
() => {
  const [value, setValue] = useState("");
  const [errorMessage, setErrorMessage] = useState();
  const onChange = ({ value, error }) => {
    setValue(value);
    setErrorMessage(error == undefined ? "" : "Error onChange: invalid email");
  };
  const onBlur = ({ value, error }) => {
    setValue(value);
    setErrorMessage(error == undefined ? "" : "Error onBlur: invalid email");
  };
  const callbackFunc = (newValue) => {
    const result = new Promise((resolve) =>
      setTimeout(() => {
        resolve(
          newValue
            ? countries.filter((option) =>
                option.toUpperCase().includes(newValue.toUpperCase())
              )
            : countries
        );
      }, 1500)
    );
    return result;
  };

  const validEmail = new RegExp("^arn" );
  return (
    <DxcInset space="2rem">
      <DxcTextInput
        value="*"
        label="Enter your email"
        onChange={onChange}
        onBlur={onBlur}
        error={errorMessage}
        pattern={validEmail}
        suggestions={callbackFunc }
        clearable
      />
    </DxcInset>
  );
}
```

Example:
1. Create a new React App using `create-react-app`.
2. Install the `@dxc-technology\halstack-react` dependencies and run the app. `6.2.2`
3. Click on '...'.
4. Scroll down to '...'.
5. See the error.

**Expected behaviour**
When Text Input has invaild pattern value inside input box on click - we end-up white screen & error...

**Screenshots**

![image](https://user-images.githubusercontent.com/53425981/206841275-a2bd898a-dcb6-4272-84c2-cb5d9f06d642.png)

**Comment by HanojHanu** [comment] 2022-12-07 17:04
@kukoc @raquelarrojo 

Please any one help me on this...

**Comment by Lisa159** [comment] 2022-12-09 08:27
Hi @HanojHanu,

You are not able to clear the input because of `value="*"`. As your component is controlled, you need to use the `useState` to 
update the value as `value={value}`.

**Comment by HanojHanu** [comment] 2022-12-10 08:09
in Realms Application, this happing..

```jsx
() => {
  const denyAclPolicy = {
    aclStatement: [
      {
        Sid: "Assure Platform Default Deny",
        Action: "*",
        Effect: "Deny",
        Resource: ["*"],
      },
    ],
  };

  const [value, setValue] = useState("*");
  const [statement, setStatement] = useState(denyAclPolicy.aclStatement);
  const [errorMessage, setErrorMessage] = useState();
  const onChange = ({ value, error }) => {
    setValue(value);
    setErrorMessage(error == undefined ? "" : "Error onChange: invalid email");
  };
  const onBlur = ({ value, error }) => {
    setValue(value);
    setErrorMessage(error == undefined ? "" : "Error onBlur: invalid email");
  };
  
  
  const suggestions_resource = (newValue) => {
    const result = new Promise((resolve) =>
      setTimeout(() => {
        resolve(
          newValue
            ? statement.Resource.filter((option) =>
                option.toUpperCase().includes(newValue.toUpperCase())
              )
            : statement.Resource 
        );
      }, 1500)
    );
    return result;
  };
  

  const resource_pattern = new RegExp("^arn" );
  return (
    <>
       {statement &&
          statement.Resource &&
          statement.Resource.map((item, i) => (
            <DxcInset space="2rem">
              <DxcTextInput
                value={item}
                label="Enter your email"
                onChange={onChange}
                onBlur={onBlur}
                error={errorMessage}
                pattern={resource_pattern}
                suggestions={suggestions_resource}
                clearable
              />
            </DxcInset>
         ))}
     </>
  );
}
```

**Comment by HanojHanu** [comment] 2022-12-10 08:22
// Auto suggestion - resource input 

/**
 * There is small issue with the suggestions 
 * Suggestions not supporting clearable prop for value which has invalid pattern inside TextInput
 */
 
 // After add comment to prop "suggestions" it is working...
 
``` jsx
    <DxcTextInput
            value={item}
            label="Enter your email"
            onChange={onChange}
            onBlur={onBlur}
            error={errorMessage}
            pattern={resource_pattern}
            // suggestions={suggestions_resource}
            clearable
          />
    </DxcInset>
```

**Comment by HanojHanu** [comment] 2022-12-10 08:29
![image](https://user-images.githubusercontent.com/53425981/206841112-73af95cc-c59f-4831-82bd-cb7fb0b82cb0.png)

**Comment by HanojHanu** [comment] 2022-12-10 08:35
``` cmd
Uncaught SyntaxError: Invalid regular expression: /*/: Nothing to repeat (at Suggestion.js:26:1)
    at new RegExp (<anonymous>)
    at Suggestion (Suggestion.js:26:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at updateFunctionComponent (react-dom.development.js:17356:1)
    at updateSimpleMemoComponent (react-dom.development.js:17215:1)
    at updateMemoComponent (react-dom.development.js:17092:1)
    at beginWork (react-dom.development.js:19135:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
    at workLoopSync (react-dom.development.js:22707:1)
    at renderRootSync (react-dom.development.js:22670:1)
    at performSyncWorkOnRoot (react-dom.development.js:22293:1)
    at react-dom.development.js:11327:1
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322:1)
    at flushSyncCallbackQueue (react-dom.development.js:11309:1)
    at discreteUpdates$1 (react-dom.development.js:22420:1)
    at discreteUpdates (react-dom.development.js:3756:1)
    at dispatchDiscreteEvent (react-dom.development.js:5889:1)
```

**Comment by Lisa159** [comment] 2022-12-12 12:42
Hi @HanojHanu,

We have been checking this issue and the problem is related with the character `*` inside the suggestions as it is reading it as a regex expression.

I will create an issue about this.

**Comment by Lisa159** [comment] 2022-12-12 13:01
I will close this issue and continue on #1416.

**Closed by Lisa159** 2022-12-12 13:01 UTC
