### ISSUE TITLE
tabIndex not supported on <DXCRadio> component

### ISSUE THREAD

**Issue by ppurumala** [dxc-technology/halstack-react#376] opened 2021-09-07 09:26 UTC
**Describe the bug**
tabIndex attribute not supported on <DXCRadio> component.

**To Reproduce**
Include 2 DXCRadio component on the screen. when tabbing through the fields the focus comes on the first radio button, However when pressing tab again, is jumping to next HTML Component but skipping the second radio button

**Expected behavior**
When pressing tab button, the focus should come to the first radio button (which is happening) and pressing tab again should take the focus to next radio button (this is not happening currently). 

This can be achieved, by having a tabindex attribute on <DxcRadio> component. like we have for <DxcCheckbox> component.

**Comment by sponnuswamydxc** [comment] 2021-12-14 06:33
@jsardid do we have any progress on this issue ?

**Comment by aweell** [comment] 2021-12-14 08:52
Hello @ppurumala and @sponnuswamydxc,

When operating through the keyboard with a `radio-group` this is the expected behavior. To move the focus to the next option of the group using the keyboard you need to use `down arrow` or `right arrow`. Pressing `tab` when the focus is in the `radio-group` will move the focus to the next component.

As a reference, we use the [WAI-ARIA 3.18 Radio Group design pattern](https://www.w3.org/TR/wai-aria-practices-1.2/#radiobutton) and there's also available a [working example using a roving tabindex technique](https://www.w3.org/TR/wai-aria-practices-1.2/examples/radio/radio.html).

Since this behavior is correctly working in the [radio group example of the React documentation](https://developer.dxc.com/tools/react/3/#/components/radio) and we don't consider this as a bug **I close the issue**. Please let us know if you face any issue using keyboard arrows to operate the `radio-group` component.

**Closed by aweell** 2021-12-14 08:52 UTC
