### ISSUE TITLE
DXCTable not responsive

### ISSUE THREAD

**Issue by ppurumala** [dxc-technology/halstack-react#220] opened 2020-12-03 12:51 UTC
DXCTable not responsive. 
In attached image, the table has few more columns on the right. They are not visible?

![TableNotReponsive](https://user-images.githubusercontent.com/72923647/101020298-48ef3400-3594-11eb-8b09-140c87b98975.jpg)

Can you please tell if this is a issue of DXC Table or is this something we can work at our end?

**Comment by pwadhwani** [comment] 2021-05-25 15:11
Hi @aweell,, Could you please provide updates on this issue.

**Comment by marcialfps** [comment] 2021-06-30 08:19
Could you please tell me which version of the CDK you are using? 
Thank you.

**Comment by ppurumala** [comment] 2021-06-30 10:08
We are using:
"@dxc-technology/halstack-client": "1.1.6",
"@dxc-technology/halstack-react": "0.0.0-1ae1a10",

Its next version of 3.2.0. 
Are you suggesting that,  this is already there in 3.2.0? Please tell.

**Comment by marcialfps** [comment] 2021-06-30 12:03
I am trying to reproduce the problem in the latest version (0.0.0-8c89dca) but in all cases a scroll is added to display the whole table.

Please try using:
`"@dxc-technology/halstack-react": "0.0.0-8c89dca",`

**Comment by rahul69-8305397710** [comment] 2021-07-20 11:18
We have verified the issue of table in new library which is resolved. but our 2 screen getting distorted due to accordion after adding new library. issue is observed in accordion only.. please find the attached screen shots.
with old version it is working fine... 
![image](https://user-images.githubusercontent.com/87701965/126315164-b2d47f0b-d4d8-4c16-8c50-36a3500d88b4.png)
![image](https://user-images.githubusercontent.com/87701965/126315239-f5b8dd66-16b3-4513-ba00-69386a41a94e.png)

**Comment by marcialfps** [comment] 2021-07-21 09:20
If the problem is not related to this issue please open another one where it is explained in more detail. I understand that the original issue is resolved, so I will close this one. 

Thank you ✌🏼

**Closed by marcialfps** 2021-07-21 09:20 UTC
